-
  branches:
    except:
      - release

  skip_tags: true

  configuration: Debug

  image: Visual Studio 2017

  build_script:
   # - cmd: msbuild /t:restore ./src/Sprint.Filter.sln
    #- cmd: msbuild /t:build /p:Configuration=Debug /v:Minimal ./src/Sprint.Filter.sln
    - cmd: dotnet restore -v m  ./src/Sprint.Filter.sln
    - cmd: dotnet build  -v m -c Debug ./src/Sprint.Filter.sln
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-beta ./src/Sprint.Filter/Sprint.Filter.csproj
   # - cmd: msbuild /t:pack /p:IncludeSymbols=true /p:Configuration=Debug /p:PackageOutputPath=../../artifacts ./src/Sprint.Filter/Sprint.Filter.csproj
       
  artifacts:
    - path: "./artifacts/*.*"
-
  branches:
    only:
      - release

  configuration: Release

  image: Visual Studio 2017

  build_script:
    - cmd: dotnet restore -v m  ./src/Sprint.Filter.sln
    - cmd: dotnet build  -v m -c Release ./src/Sprint.Filter.sln
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts ./src/Sprint.Filter/Sprint.Filter.csproj
      
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: 642CQyNRZfe9fDFvEdV5ISN5ggxFvY82meXc2zwaj18sG96g4cR+sfi8xG/9enGC
      skip_symbols: false
      artifact: /.*\.nupkg/